name: deploy-production

on:
  push:
    branches: [shielded-outputs-audit-ci-cd-test]
    tags: ['v*']

permissions:
  id-token: write
  contents: read

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Node.js 22.x
        # https://github.com/actions/setup-node/releases/tag/v4.4.0
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22.x

      - name: Configure AWS Credentials
        # https://github.com/aws-actions/configure-aws-credentials/releases/tag/v4.2.1
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::769498303037:role/ShieldedOutputsAuditGitHubActionsRoleProduction

      - name: Build
        run: make build site=production

      - name: Deploy
        run: make deploy site=production
